### ISSUE TITLE
parse exception in the ddc generated files

### ISSUE THREAD

**Issue by devoncarew** [flutter/atom-flutter#18]
A git bisect points to this commit in ddc: https://github.com/dart-lang/dev_compiler/commit/c9d909ced98dea2aefe20322a59d18fbab2d93b2.

**Comment by devoncarew** [comment]
<img width="459" alt="screen shot 2015-12-11 at 6 30 38 am" src="https://cloud.githubusercontent.com/assets/1269969/11746037/bc89d898-9fd0-11e5-9986-72afecb2b07d.png">

**Comment by devoncarew** [comment]
SyntaxError: Unexpected token '{'
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:413:25)
at Object.keys.forEach.Object.defineProperty.value [as .js](/Users/devoncarew/tools/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17
at require (module.js:384:17)
at Object.&lt;anonymous&gt; (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/entry_all.js:16:1)
at Module._compile (module.js:434:26)
at Object.keys.forEach.Object.defineProperty.value [as .js](/Users/devoncarew/tools/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)

**Comment by devoncarew** [comment]
Looks like somewhere in `runtime/dart/_interceptors.js`.

**Comment by devoncarew** [comment]
Should be addressed by the latest version of dev_compiler, run with the `--no-destructure-named-params` flag.

**Comment by jmesserly** [comment]
oh nice!
