### ISSUE TITLE
investigate why the plugin can't install packages when compiled with ddc

### ISSUE THREAD

**Issue by devoncarew** [flutter/atom-flutter#54]
Uncaught TypeError: Bad argument

```
At /Users/devoncarew/tools/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:260

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Users/devoncarew/tools/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Users/devoncarew/tools/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Function.new (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/js.js:28:26)
    at Function.create (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/atom/atom.js:558:51)
    at ProcessRunner.execStreaming (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/atom/node/process.js:144:47)
    at ProcessRunner.execSimple (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/atom/node/process.js:137:27)
    at _installPackage (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/atom/utils/package_deps.js:35:19)
    at checkAndCall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:454:16)
    at Object.dcall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:460:12)
    at /Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1895:52
    at Function.sync (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1794:24)
    at /Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1895:28
    at Function.sync (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1794:24)
    at /Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1903:23
    at checkAndCall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:454:16)
    at Object.dcall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:460:12)
    at _RootZone.runUnaryGuarded (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:5570:23)
    at /Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:5602:36
    at checkAndCall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:454:16)
    at Object.dcall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:460:12)
    at Function.doWhile (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1908:14)
    at Function.forEach (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:1893:26)
    at /Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/atom/utils/package_deps.js:27:29
    at checkAndCall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:454:16)
    at Object.dcall (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/_runtime.js:460:12)
    at _RootZone.runUnary (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:5631:80)
    at handleValueCallback (/Users/devoncarew/projects/flutter/atom-flutter-dev/web/ddc/dev_compiler/runtime/dart/async.js:2427:45)
```

**Comment by devoncarew** [comment]
fixed in the latest DDC
