### ISSUE TITLE
When I run the atom, this error message is displayed

### ISSUE THREAD

**Issue by rezabagheri** [flutter/atom-flutter#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [flutter](https://github.com/flutter/atom-flutter) package 0.2.7

### Stack Trace

Uncaught 

```
At /home/reza/.atom/packages/atom-flutter/web/entry.dart.js:6953

Instance of 'Event'
    at Object.wrapException (/packages/atom-flutter/web/entry.dart.js:7832:17)
    at /packages/atom-flutter/web/entry.dart.js:11887:19)
    at Object._microtaskLoop (/packages/atom-flutter/web/entry.dart.js:10087:27)
    at StaticClosure.dart._startMicrotaskLoop (/packages/atom-flutter/web/entry.dart.js:10093:11)
    at /packages/atom-flutter/web/entry.dart.js:7298:23)
    at /packages/atom-flutter/web/entry.dart.js:8882:29)
    at /packages/atom-flutter/web/entry.dart.js:6944:25)
    at Object._callInIsolate (/packages/atom-flutter/web/entry.dart.js:6584:28)
    at dart.invokeClosure (/packages/atom-flutter/web/entry.dart.js:7976:20)
    at /packages/atom-flutter/web/entry.dart.js:7997:18
```

### Commands

```
     -1:12.1.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
flutter 0.2.7 
atom-toolbar 0.1.6 
busy-signal 2.0.1 
dart 1.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
wordpress 0.2.0 
```

**Comment by swarupbhc** [comment]
@rezabagheri This project is discontinued
